const COLOR = {
  BODY: '#282C39',
  DESCRIPTION: '#4F5464',
  TERTIARY: '#969FBE',
  BRIGHT: '#FFFFFF',
  SHADE: '#EBF0F4',
  BACKGROUND: '#F4F7FB',
  DISABLED: '#EBEBEB',
  TINT: '#EBEBEB',
  ACCENT: '#FF0B5E',
  ACCENT_SECONDARY: '#3757FF',
  ACCENT_TERTIARY: '#F8B62D',
  ACCENT_FORTY: '#FF9F59',
  SUCCESS: '#0EBA75',
  INFORMATION: '#D4EBFF',
  WARNING: '#FB27FF',
  DANGER: '#E4002C',
}

export type COLOR_TYPE = keyof typeof COLOR

export { COLOR }
